// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTXV0jQSj6Au8IyKBpFO04dsWtJiZoLfE',
    appId: '1:343039741050:web:053a778d8c9065afb13fc3',
    messagingSenderId: '343039741050',
    projectId: 'todo-app-426615',
    authDomain: 'todo-app-426615.firebaseapp.com',
    storageBucket: 'todo-app-426615.appspot.com',
    measurementId: 'G-HDGGVX6H89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkRECUejP0fYhOmQTz8LRX-8HpQMh3LW0',
    appId: '1:343039741050:android:1bc9c0d351a81deab13fc3',
    messagingSenderId: '343039741050',
    projectId: 'todo-app-426615',
    storageBucket: 'todo-app-426615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2D6a3M2y4PLGEzbg9z8o6Kwvb6sQW-80',
    appId: '1:343039741050:ios:a6a00929937b8875b13fc3',
    messagingSenderId: '343039741050',
    projectId: 'todo-app-426615',
    storageBucket: 'todo-app-426615.appspot.com',
    androidClientId: '343039741050-sve6qhih9f59a1uef0ttcvj4mdm3eudr.apps.googleusercontent.com',
    iosClientId: '343039741050-imgr0ip059mjunncv2ithpj6d38b5oju.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2D6a3M2y4PLGEzbg9z8o6Kwvb6sQW-80',
    appId: '1:343039741050:ios:a6a00929937b8875b13fc3',
    messagingSenderId: '343039741050',
    projectId: 'todo-app-426615',
    storageBucket: 'todo-app-426615.appspot.com',
    androidClientId: '343039741050-sve6qhih9f59a1uef0ttcvj4mdm3eudr.apps.googleusercontent.com',
    iosClientId: '343039741050-imgr0ip059mjunncv2ithpj6d38b5oju.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTXV0jQSj6Au8IyKBpFO04dsWtJiZoLfE',
    appId: '1:343039741050:web:c2d68ed42fef3dbdb13fc3',
    messagingSenderId: '343039741050',
    projectId: 'todo-app-426615',
    authDomain: 'todo-app-426615.firebaseapp.com',
    storageBucket: 'todo-app-426615.appspot.com',
    measurementId: 'G-S81GRK34Y0',
  );
}
